import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "./components/SessionProvider";
import Navbar from "./components/Navbar";
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<p>Loading</p>}>
          <SessionProvider>
            <div className="navbar-container">
              <Navbar />
            </div>
            <div className="content-container">
              {children}
            </div>
          </SessionProvider>
        </Suspense>
        
      </body>
    </html>
  );
}
